### ISSUE TITLE
Shameful

### ISSUE THREAD

**Issue by yegors** [g3th/Windscribe-Signup#1]
Unsure why you think it's a good idea to publish tools that abuse a free service, and break ToS, but it's not a good idea and actually illegal.

**Comment by Auditormadness9** [comment]
Abuse is gonna happen manually anyway, just that geniuses like this come up with ways to ease up life for our fingers. If you're so hurt on behalf of a company who doesn't even know you, make a counter to this yourself and propose it to them.
